import { Color } from '@material-ui/lab';

export default {
  prefersDarkMode: 'prefersDarkMode',
  action: 'action',
  update: 'update',
  delete: 'delete',
  refetch: 'refetch',
  sign: 'sign',
  token: 'token',
  success: <Color>'success',
  error: <Color>'error',
  info: <Color>'info',
  warning: <Color>'warning',
  admin: 'admin',
  redirect: 'redirect',
  dashboard: 'dashboard',
  category: 'category',
  Category: 'Category',
  categories: 'categories',
  CATEGORY: 'CATEGORY',
  user: 'user',
  users: 'users',
  User: 'User',
  USER: 'USER',
  password: 'password',
};
