import { Colorize } from '@material-ui/icons';
import { Color } from '@material-ui/lab';

export default {
  prefersDarkMode: 'prefersDarkMode',
  action: 'action',
  update: 'update',
  delete: 'delete',
  refetch: 'refetch',
  sign: 'sign',
  token: 'token',
  success: <Color>'success',
  error: <Color>'error',
  info: <Color>'info',
  warning: <Color>'warning',
  admin: 'admin',
  redirect: 'redirect',
  dashboard: 'dashboard',
  questions: 'questions',
  question: 'question',
  sections: 'sections',
  section: 'section',
  category: 'category',
  categories: 'categories',
  user: 'user',
  users: 'users',
  Question: 'Question',
  Section: 'Section',
  Category: 'Category',
  User: 'User',
  USER: 'USER',
  CATEGORY: 'CATEGORY',
  SECTION: 'SECTION',
};
